### ISSUE TITLE
Feature: Enable scrolling for targets in a different container

### ISSUE THREAD

**Issue by misaizdaleka** [nicky-lenaers/ngx-scroll-to#20]
Hi, 
So in one div I have my anchors which I click for scrolling and in another one are the targets to scroll to. 
This usecase is not working. Here's a plunkr for you to see:
https://plnkr.co/edit/y345JeEKeOz4pv9maZaV?p=preview

Am I setting something wrong, or is it not possble?

Thanks

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

<pre><code>
Angular version: 4

</code></pre>

**Comment by nicky-lenaers** [comment]
Hi @misaizdaleka , thank you for your issue. As of this moment, setting a custom scroll container is not possible. You're usecase seems a valid one to enable this feature. In short, these are the requirements for this feature:

- A new directive, something like `[ngx-scroll-to-container]`
- A check whether the container is scrollable
- Some tests to verify the behaviour

You're welcome to give it a go, otherwise I'll be developing this feature as soon as I can.

**Comment by nicky-lenaers** [comment]
@misaizdaleka I'm happy to announce that this feature has been merged in the current stable release [`0.4.0`](https://github.com/nicky-lenaers/ngx-scroll-to/releases). Please see the [CHANGELOG](https://github.com/nicky-lenaers/ngx-scroll-to/blob/master/CHANGELOG.md) for more details and check out the fresh release at [NPM](https://www.npmjs.com/package/@nicky-lenaers/ngx-scroll-to).

Thanks again for your issue reporting! Hopefully this module will serve you well 😄
