### ISSUE TITLE
Can't bind to 'ngx-scroll-to' since it isn't a known property of 'button'

### ISSUE THREAD

**Issue by sivan123** [nicky-lenaers/ngx-scroll-to#70]
Getting this strange error and unable to make it work. 
followed the basic steps in the doc.

VM8855 core.js:1655 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'ngx-scroll-to' since it isn't a known property of 'button'. ("            <td>{{user.lastName}}</td>
                <td>
                  <button type="button" [ERROR ->][ngx-scroll-to]="'userdetails'" class="btn btn-info btn-sm" aria-label="Left Align" (click)="showUser"): ng:///ArgModule/UsermanagementComponent.html@30:40
Error: Template parse errors:
Can't bind to 'ngx-scroll-to' since it isn't a known property of 'button'. ("            <td>{{user.lastName}}</td>

**Comment by nicky-lenaers** [comment]
@sivan123 Thank you for your issue. This issue, however, is a not a problem with this module. My educated guess is that somewhere you forgot to `import` or `export` the proper module. There are many issues to be found across the web, inclusing [here](https://stackoverflow.com/questions/43522877/cant-bind-to-x-since-it-isnt-a-known-property-of-y?rq=1), (here)[https://stackoverflow.com/questions/38960141/angular2-rc5-cant-bind-to-property-x-since-it-isnt-a-known-property-of-chi] and (here)[https://stackoverflow.com/questions/45303404/angular-2-cant-bind-to-uploader-since-it-isnt-a-known-property-of-input?noredirect=1#comment77574329_45303404]. 

Closing this issue due to unrelated nature of issue.

If you still find yourself not being able to make this work, please provide a Stackblitz/Plunkr example in a new issue.

**Comment by casvanluijtelaar** [comment]
this is an issue. however the execution will still work.
![image](https://user-images.githubusercontent.com/46999476/60595129-b0ed8980-9da6-11e9-9a1d-20333e2b7eaf.png)

**Comment by t0921988961** [comment]
I have same question, but i find the problem,
**### 1.First, Please make sure your app.module.ts**
`import { ScrollToModule } from '@nicky-lenaers/ngx-scroll-to';
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    ...
    ScrollToModule.**_forRoot_**(  )
  ],
  providers: [],
  bootstrap: [AppComponent]
})
`

**### 2.In your Feature.module.ts , Please make sure below setting **
**Attention => inside @NgModule no need add **forRoot**( )**
`
import { ScrollToModule } from '@nicky-lenaers/ngx-scroll-to';

@NgModule({
  declarations: [ aaaaComponent, bbbbComponent ],
  imports: [
     ...
    **ScrollToModule**
  ]
})
export class MaterialsModule { }
`

******
My Feature.module.ts 
1.forget import {  ScrollToModule  }
2.@NgModule => imports no need add forRoot( )

**Comment by pragati-dugar-frequence** [comment]
did'nt work for me
