### ISSUE TITLE
[ngx-scroll-to] issues with gifs

### ISSUE THREAD

**Issue by GregSithole** [nicky-lenaers/ngx-scroll-to#93]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

The issue happens when I have multiple gifs in a Component and I use `[ngx-scroll-to]="'#section'"`, 
which causes the browser to lag on that section as the scroll is initiated. 

## Expected behavior

My desire is for the scroll, to work smoothly and not lag on the Gif sections as this makes it appear as though it's broken. 

## Minimal reproduction of the problem with instructions

Well the website is currently hosted, Please visit https://entrostat.xyz and click on the navigation buttons on the navigation bar, but specifically the "work" navigation

## Environment

<pre><code>
Angular version: 5.2.5

Your version of `@nicky-lenaers/ngx-scroll-to`: 0.6.0

Browser:
- [x] Chrome (desktop) version  67.0.3396.99
- [x ] Chrome (Android) version XX
- [x] Chrome (iOS) version 67.0.3396.87
- [x] Firefox version 61.0.1
- [ ] Safari (desktop) version XX
- [x] Safari (iOS) version 604.1
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.8.0
- Platform:  Windows

Others:

</code></pre>

**Comment by nicky-lenaers** [comment]
@GregSithole I've just released [version 1.1.0](https://github.com/nicky-lenaers/ngx-scroll-to/releases/tag/1.1.0), which includes passive event listeners. I've noticed your page lags even when using the mousewheel to scroll. I think you should be looking at decreasing the gif-intensive parts rather than a fix for this package.

Let me know if the passive event listeners have done any good. Closing this issue.
